apiVersion: v1
kind: Service
metadata:
  name: devops-app
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
    - protocol: TCP
      port: 3000        # Cluster-internal port
      targetPort: 3000  # Container port
      nodePort: 30007   # Port to access on Minikube host
